# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KurkowskiSeth_Parkaholic_DVP4' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KurkowskiSeth_Parkaholic_DVP4
pod ‘Firebase/Core’
end
